--- #YAML:1.0
name:               Net-SSLeay-OO
version:            0.02
abstract:           OO Calling Method for Net::SSLeay
author:
    - Catalyst SRS Team <team-srs@catalyst.net.nz>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:        0.54
    Net::SSLeay:  1.35
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
