---
abstract: 'OO Calling Method for Net::SSLeay'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-SSLeay-OO
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.54
  Net::SSLeay: 1.35
  perl: 5.008005
version: 0.01
